apiVersion: v1
kind: Namespace
metadata:
  name: e5-mistral-7b-instruct
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: e5-mistral-7b-instruct
  namespace: e5-mistral-7b-instruct
spec:
  model:
    name: e5-mistral-7b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
