apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-2-90b-vision-instruct-fp8
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  displayName: meta.llama-3.2-90b-vision-instruct-fp8
  vendor: meta
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://RedHatAI/Llama-3.2-90B-Vision-Instruct-FP8-dynamic
    path: /raid/models/meta/llama-3-2-90b-vision-instruct-fp8-dynamic
