apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferenceservice.ome.io
  annotations:
    cert-manager.io/inject-ca-from: ome/serving-cert
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: ome-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-ome-io-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.ome-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - ome.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
