apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-oss-120b
spec:
  vendor: openai
  disabled: false
  version: "1.0.0"
  displayName: openai.gpt-oss-120b
  modelCapabilities:
    - TEXT_TO_TEXT
  modelFramework:
    name: transformers
    version: "4.55.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelArchitecture: GptOssForCausalLM
  storage:
    storageUri: hf://openai/gpt-oss-120b
    path: /raid/models/openai/gpt-oss-120b
    key: "hf-token"
