apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.modelAgent.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: "ome-model-agent-daemonset"
