apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: phi-3-vision-128k-instruct
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  disabled: false
  displayName: microsoft.phi-3-vision-128k-instruct
  storage:
    storageUri: hf://microsoft/Phi-3-vision-128k-instruct
    path: /raid/models/microsoft/phi-3-vision-128k-instruct
  vendor: microsoft
  version: "0.1"
