---
apiVersion: v1
kind: Namespace
metadata:
  name: deepseek-r1
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: deepseek-r1
  namespace: deepseek-r1
spec:
  # model is required, if kind is not specified, the controller will automatically use ClusterBaseModel
  model:
    name: deepseek-r1
  # runtime is optional, if not specified, the controller will automatically select a compatible runtime
  # otherwise, please ensure that the runtime is compatible with the model and actually exists
  runtime:
    name: srt-deepseek-rdma
  engine:
    minReplicas: 1
    maxReplicas: 1
