apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: ome
data:
  ingress: |-
    {
        "ingressGateway" : "knative-serving/knative-ingress-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "knative-serving/knative-local-gateway",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "knativeLocalGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "omeIngressGateway" : "",
        "ingressDomain"  : "svc.cluster.local",
        "ingressClassName" : "istio",
        "additionalIngressDomains" : null,
        "domainTemplate": "{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}",
        "urlScheme": "http",
        "disableIstioVirtualHost": false,
        "pathTemplate": "",
        "disableIngressCreation": true,
        "enableGatewayAPI": false
    }

  deploy: |-
    {
      "defaultDeploymentMode": "RawDeployment"
    }

  metricsAggregator: |-
    {
      "enableMetricAggregation": "false",
      "enablePrometheusScraping" : "false"
    }

  modelInit: |-
    {
        "image" : "ghcr.io/moirai-internal/ome-agent:v0.1.5",
        "memoryRequest": "320Gi",
        "memoryLimit": "320Gi",
        "cpuRequest": "15",
        "cpuLimit": "15",
        "compartmentId": "ocid1.compartment.oc1..aaaaaaaarncfmdarfvbvhfj2oknyuvvftcp4p6ra77xlswftk67kcffmm2xq",
        "authType" : "InstancePrincipal",
        "vaultId": "ocid1.vault.oc1.eu-frankfurt-1.ens4gnknaaec4.abtheljrqneswo524ce3ytfqv3wqdjz4yi2drovyjnuo5lghz2fr76a7l7lq",
        "region": "eu-frankfurt-1"
    }

  multinodeProber: |-
    {
      "image" : "ghcr.io/moirai-internal/multinode-prober:v0.1.5",
      "memoryRequest": "100Mi",
      "memoryLimit": "100Mi",
      "cpuRequest": "100m",
      "cpuLimit": "100m",
      "startupFailureThreshold": 150,
      "startupPeriodSeconds": 30,
      "startupTimeoutSeconds": 60,
      "startupInitialDelaySeconds": 200,
      "unavailableThresholdSeconds": 1800
    }

  kedaConfig: |-
    {
      "enableKeda" : true,
      "promServerAddress": "http://prometheus-operated.monitoring.svc.cluster.local:9090",
      "customPromQuery": "",
      "scalingThreshold": "10",
      "scalingOperator": "GreaterThanOrEqual"
    }
