---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-4-scout-17b-16e-instruct
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    ome.io/deploymentMode: RawDeployment
  name: llama-4-scout-17b-16e-instruct
  namespace: llama-4-scout-17b-16e-instruct
spec:
  model:
    name: llama-4-scout-17b-16e-instruct
  runtime:
    name: srt-llama-4-scout-17b-16e-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
