---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-3-2-1b-instruct
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-2-1b-instruct
  namespace: llama-3-2-1b-instruct
spec:
  model:
    name: llama-3-2-1b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
