apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ome.io_inferenceservices.yaml
  - ome.io_clusterservingruntimes.yaml
  - ome.io_servingruntimes.yaml
  - ome.io_basemodels.yaml
  - ome.io_clusterbasemodels.yaml
  - ome.io_benchmarkjobs.yaml
  - ome.io_acceleratorclasses.yaml
